#!/bin/bash

echo "You challenge the Queen of Hearts to a game of croquet."
echo "You beat her."
echo "That turns out to have been an unwise strategy, for she is not pleased."
echo "She yells, 'Off with your head!'"
echo "Fortunately the executioner is busy trying to decapitate a grinning cheshire cat with no body, and doesn't have time to deal with you."
